DROP DATABASE IF EXISTS partyGame;
CREATE DATABASE partyGame;
use partyGame
DROP TABLE IF EXISTS game;
CREATE TABLE game (

	gameId INT NOT NULL AUTO_INCREMENT,	 
	lastConnected DATETIME NOT NULL,
	firstConnected DATETIME NOT NULL,
	secret VARCHAR(255) NOT NULL, 
	code VARCHAR(4) NOT NULL UNIQUE, 
	answerType INT NULL,
	PRIMARY KEY (gameId)

);

DROP TABLE IF EXISTS user;
CREATE TABLE user (

	gameId INT NOT NULL,
	username VARCHAR(15) NOT NULL,
	score INT NOT NULL,
	answer VARCHAR(50) NULL,
	sessionId VARCHAR(255) NOT NULL,
	PRIMARY KEY (gameId, username),
	FOREIGN KEY (gameId) REFERENCES game(gameId) ON DELETE CASCADE ON UPDATE CASCADE

);

DROP EVENT IF EXISTS PERGE_GAMES; 

CREATE EVENT PERGE_GAMES
ON SCHEDULE EVERY 1 MINUTE
DO DELETE game
FROM game
WHERE lastConnected < NOW() - INTERVAL 30 SECOND;

SET GLOBAL event_scheduler = ON;